import { Poppins } from "next/font/google";
import Nav from "../components/Nav";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});


export const metadata = {
  title: "Kara App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} max-w-120 mx-auto antialiased`}>
        {children}
        <Nav />
      </body>
    </html>
  );
}
